START TRANSACTION;

SELECT COUNT(*) AS NUMBER_OF_RECORDS FROM TBL_TRANSACTION;

DELETE FROM TBL_TRANSACTION
WHERE EMPLOYEE_NUMBER IN
(
SELECT T.EMPLOYEE_NUMBER AS T_NUMBER
FROM TBL_EMPLOYEE E
RIGHT JOIN TBL_TRANSACTION T
ON E.EMPLOYEE_NUMBER = T.EMPLOYEE_NUMBER
WHERE E.EMPLOYEE_NUMBER IS NULL
);

SELECT COUNT(*) AS NUMBER_OF_RECORDS FROM TBL_TRANSACTION;

ROLLBACK;

--COMMIT;