CREATE SEQUENCE PSeq
START WITH 1 
INCREMENT BY 4;

ALTER TABLE PTBL_PRODUCT
ADD Seq_Column DECIMAL(7,0);

UPDATE PTBL_PRODUCT
SET SEQ_COLUMN = pseq.nextval
WHERE SEQ_COLUMN IS NULL;


ALTER TABLE PTBL_PRODUCT 
MODIFY (seq_column DECIMAL(7,0) DEFAULT pseq.NEXTVAL);



SELECT *
FROM PTBL_PRODUCT;
