CREATE TABLE TBL_DEPARTMENT AS(
SELECT DEPARTMENT
FROM(
SELECT DEPARTMENT, COUNT(*) AS NUMBER_PER_DEPARTMENT
FROM TBL_EMPLOYEE
GROUP BY DEPARTMENT))
;

ALTER TABLE TBL_DEPARTMENT
ADD DEPARTMENT_HEAD VARCHAR2(20);